#!/usr/bin/env python3

"""Generate tutorial/reference markdown skeletons for RedCap project docs."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Milestone:
    """Represent a parsed milestone heading."""

    title: str
    source_file: str


def parse_args() -> argparse.Namespace:
    """Build and parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Generate RedCap tutorial/reference markdown skeletons from plan files."
    )
    parser.add_argument(
        "--baseline-plan",
        default="agent_doc/Project_management/Simluation_v2.md",
        help="Baseline milestone/spec markdown file.",
    )
    parser.add_argument(
        "--execution-plan",
        default="agent_doc/Project_management/projects/redcap_mmtc_priority_execution_v1/project_plan.md",
        help="Execution-plan markdown file.",
    )
    parser.add_argument(
        "--tutorial-output",
        default="doc/tutorial_redcap_rfsim.md",
        help="Output path for tutorial skeleton.",
    )
    parser.add_argument(
        "--reference-output",
        default="doc/reference_redcap_functions.md",
        help="Output path for reference skeleton.",
    )
    return parser.parse_args()


def read_text(path: Path) -> str:
    """Read UTF-8 text from markdown path."""
    return path.read_text(encoding="utf-8")


def extract_milestones(path: Path) -> list[Milestone]:
    """Extract milestone headings from markdown content."""
    content = read_text(path)
    milestones: list[Milestone] = []

    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line.startswith("## Milestone"):
            continue
        title = line.lstrip("#").strip()
        milestones.append(Milestone(title=title, source_file=str(path)))

    return milestones


def merge_milestones(*groups: list[Milestone]) -> list[Milestone]:
    """Merge milestone lists while preserving first-seen order."""
    merged: list[Milestone] = []
    seen: set[str] = set()

    for milestones in groups:
        for milestone in milestones:
            if milestone.title in seen:
                continue
            merged.append(milestone)
            seen.add(milestone.title)

    return merged


def render_milestone_list(milestones: list[Milestone]) -> str:
    """Render milestone bullets for markdown output."""
    if not milestones:
        return "- [No milestone heading found in source plans]"

    lines = []
    for milestone in milestones:
        lines.append(f"- [{milestone.title}] (source: `{milestone.source_file}`)")
    return "\n".join(lines)


def build_tutorial_skeleton(
    baseline_plan: Path,
    execution_plan: Path,
    milestones: list[Milestone],
) -> str:
    """Build tutorial markdown skeleton text."""
    milestone_lines = render_milestone_list(milestones)

    return f"""# RedCap RFsim Tutorial (Skeleton)

## Document Metadata
- Generated by: `scripts/gen_doc_skeleton.py`
- Baseline Plan: `{baseline_plan}`
- Execution Plan: `{execution_plan}`

## Milestone Snapshot
{milestone_lines}

## Chapter 1: Environment Setup
- [Placeholder] Docker image versions:
  - `oai-gnb`
  - `oai-nr-ue`
  - `oai-amf`
  - `oai-smf`
  - `oai-upf`
  - `oai-ext-dn`
  - `oai-flexric`
- [Placeholder] RedCap config file locations and naming rules.
- [Placeholder] Prerequisites (`Docker`, `docker compose`, `iperf3`, `Python`).

## Chapter 2: Launching rfsimulation with RedCap
- [Placeholder] gNB launch command and per-flag notes.
- [Placeholder] UE launch command and per-flag notes.
- [Placeholder] Expected attach validation markers.

## Chapter 3: UL Throughput Test Design
- [Placeholder] UL-only `iperf3` procedure.
- [Placeholder] `redcap_tput_logger.py` parsing step.
- [Placeholder] TUN route verification step.

## Chapter 4: Docker Deployment
- [Placeholder] Fixed-UE validation path (`oai-nr-ue1` + `oai-nr-ue2`).
- [Placeholder] Scalable mMTC path (`docker-compose.mmtc.yml`).
- [Placeholder] Health-check commands and expected log markers.

## Chapter 5: Integration with xApp / rApp / dApp
- [Placeholder] E2/xApp integration mapping.
- [Placeholder] dApp integration mapping.
- [Placeholder] O1/rApp status and gaps.

## Open Items
- [Placeholder] Add real commands/log examples after runtime validation.
- [Placeholder] Add clause-accurate 3GPP references (mark uncertain as [VERIFY]).
"""


def build_reference_skeleton(
    baseline_plan: Path,
    execution_plan: Path,
    milestones: list[Milestone],
) -> str:
    """Build reference markdown skeleton text."""
    milestone_lines = render_milestone_list(milestones)

    return f"""# RedCap Function Reference (Skeleton)

## Document Metadata
- Generated by: `scripts/gen_doc_skeleton.py`
- Baseline Plan: `{baseline_plan}`
- Execution Plan: `{execution_plan}`

## Milestone Snapshot
{milestone_lines}

## Chapter 1: New Function Index
- [Placeholder] Import from `scripts/output/function_index.json`.
- [Entry Template]
  - Function:
  - File:
  - Description:
  - Parameters:
  - Returns:
  - Side effects:
  - 3GPP ref:
  - Callers:
  - Callees:

## Chapter 2: State Machine and Flow Diagrams
- [Placeholder] SDT scheduler FSM (Mermaid).
- [Placeholder] RedCap RRC attach flow (Mermaid).

## Chapter 3: Compliance Gap Register
| Feature | Status | Milestone | Notes |
|---|---|---|---|
| [Placeholder] | [Placeholder] | [Placeholder] | [Placeholder] |

## Open Items
- [Placeholder] Bind each entry to validated test evidence.
- [Placeholder] Finalize 3GPP clause references after implementation freeze.
"""


def write_text(path: Path, content: str) -> None:
    """Write UTF-8 text to path, creating parent directory as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    """Execute script entrypoint and return process exit code."""
    args = parse_args()

    baseline_plan = Path(args.baseline_plan)
    execution_plan = Path(args.execution_plan)
    tutorial_output = Path(args.tutorial_output)
    reference_output = Path(args.reference_output)

    baseline_milestones = extract_milestones(baseline_plan)
    execution_milestones = extract_milestones(execution_plan)
    merged_milestones = merge_milestones(baseline_milestones, execution_milestones)

    tutorial_content = build_tutorial_skeleton(baseline_plan, execution_plan, merged_milestones)
    reference_content = build_reference_skeleton(baseline_plan, execution_plan, merged_milestones)

    write_text(tutorial_output, tutorial_content)
    write_text(reference_output, reference_content)

    print(f"Tutorial skeleton: {tutorial_output}")
    print(f"Reference skeleton: {reference_output}")
    print(f"Milestones discovered: {len(merged_milestones)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
