#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
COMPOSE_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

TOTAL_UES="${1:-32}"
OUTPUT_FILE="${2:-$COMPOSE_DIR/docker-compose.mmtc.yml}"
BASE_FIXED_UE_COUNT="${BASE_FIXED_UE_COUNT:-28}"
START_UE_INDEX=$((BASE_FIXED_UE_COUNT + 1))

if ! [[ "$TOTAL_UES" =~ ^[0-9]+$ ]]; then
  echo "TOTAL_UES must be an integer, got: $TOTAL_UES" >&2
  exit 1
fi

if (( TOTAL_UES <= BASE_FIXED_UE_COUNT )); then
  echo "TOTAL_UES must be greater than ${BASE_FIXED_UE_COUNT} to extend the fixed-UE base compose" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/generate_mmtc_overlay.sh
# Purpose:
#   extend the fixed RedCap compose path beyond UE${BASE_FIXED_UE_COUNT}
#   while keeping the operator workflow centered on:
#     docker compose -f docker-compose.yml -f docker-compose.mmtc.yml up -d
services:
  oai-gnb:
    environment:
      MMTC_SEGV_BACKTRACE: \${MMTC_SEGV_BACKTRACE:-0}

EOF

# Keep base UE1..UE${BASE_FIXED_UE_COUNT} aligned with mMTC runtime knobs.
# These services already exist in docker-compose.yml; here we only override env.
for ((idx=1; idx<=BASE_FIXED_UE_COUNT; idx++)); do
  imsi=$(printf '001010%09d' "$idx")
  cat >> "$OUTPUT_FILE" <<EOF
  oai-nr-ue${idx}:
    environment:
      MMTC_UE_INDEX: "${idx}"
      MMTC_IMSI: "${imsi}"
      MMTC_REDCAP_ENABLE: \${MMTC_REDCAP_ENABLE:-1}
      MMTC_REDCAP_NUM_RX: \${MMTC_REDCAP_NUM_RX:-1}
      MMTC_REDCAP_HALF_DUPLEX: \${MMTC_REDCAP_HALF_DUPLEX:-1}
      MMTC_PUSCH_256QAM: \${MMTC_PUSCH_256QAM:-0}
      MMTC_TEMPLATE_CONFIG: /opt/oai-nr-ue/etc/nr-ue.yaml
      MMTC_BAND: \${MMTC_BAND:-78}
      MMTC_RF_FREQ: \${MMTC_RF_FREQ:-3630360000}
      MMTC_NUMEROLOGY: \${MMTC_NUMEROLOGY:-1}
      MMTC_N_RB_DL: \${MMTC_N_RB_DL:-106}
      MMTC_SSB_START: \${MMTC_SSB_START:-144}
      MMTC_CGCFG_NOFREE: \${MMTC_CGCFG_NOFREE:-0}
      MMTC_CGCFG_DEFER_FREE_SLOTS: \${MMTC_CGCFG_DEFER_FREE_SLOTS:-0}
      MMTC_PUCCH_COMMON_FALLBACK_BWP0: \${MMTC_PUCCH_COMMON_FALLBACK_BWP0:-0}
      MMTC_SEGV_BACKTRACE: \${MMTC_SEGV_BACKTRACE:-0}
      MMTC_PDCP_TRACE: \${MMTC_PDCP_TRACE:-0}
    volumes:
      - ../../conf_files/nrue_recap/nrue${idx}.uicc.yaml:/opt/oai-nr-ue/etc/nr-ue.yaml:ro
      - ./scripts/ue_mmtc_entrypoint.sh:/opt/oai-nr-ue/bin/entrypoint.sh:ro

EOF
done

for ((idx=START_UE_INDEX; idx<=TOTAL_UES; idx++)); do
  imsi=$(printf '001010%09d' "$idx")
  ip_last=$((149 + idx))
  telnet_port=$((8090 + idx))

  cat >> "$OUTPUT_FILE" <<EOF
  oai-nr-ue${idx}:
    image: \${REGISTRY-oaisoftwarealliance/}\${NRUE_IMG:-oai-nr-ue}:\${TAG:-develop}
    container_name: rfsim5g-oai-nr-ue${idx}_redcap
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    environment:
      MMTC_UE_INDEX: "${idx}"
      MMTC_IMSI: "${imsi}"
      MMTC_REDCAP_ENABLE: \${MMTC_REDCAP_ENABLE:-1}
      MMTC_REDCAP_NUM_RX: \${MMTC_REDCAP_NUM_RX:-1}
      MMTC_REDCAP_HALF_DUPLEX: \${MMTC_REDCAP_HALF_DUPLEX:-1}
      MMTC_PUSCH_256QAM: \${MMTC_PUSCH_256QAM:-0}
      MMTC_TEMPLATE_CONFIG: /opt/oai-nr-ue/etc/nr-ue.yaml
      MMTC_BAND: \${MMTC_BAND:-78}
      MMTC_RF_FREQ: \${MMTC_RF_FREQ:-3630360000}
      MMTC_NUMEROLOGY: \${MMTC_NUMEROLOGY:-1}
      MMTC_N_RB_DL: \${MMTC_N_RB_DL:-106}
      MMTC_SSB_START: \${MMTC_SSB_START:-144}
      MMTC_CGCFG_NOFREE: \${MMTC_CGCFG_NOFREE:-0}
      MMTC_CGCFG_DEFER_FREE_SLOTS: \${MMTC_CGCFG_DEFER_FREE_SLOTS:-0}
      MMTC_PUCCH_COMMON_FALLBACK_BWP0: \${MMTC_PUCCH_COMMON_FALLBACK_BWP0:-0}
      MMTC_SEGV_BACKTRACE: \${MMTC_SEGV_BACKTRACE:-0}
      MMTC_PDCP_TRACE: \${MMTC_PDCP_TRACE:-0}
      USE_ADDITIONAL_OPTIONS: >
        -E --rfsim -r 106 --numerology 1
        --uicc0.imsi ${imsi}
        -C \${MMTC_RF_FREQ:-3630360000}
        --ssb \${MMTC_SSB_START:-144}
        --rfsimulator.serveraddr \${MMTC_GNB_ADDR:-192.168.70.140}
        --log_config.global_log_options level,nocolor,time
        --telnetsrv --telnetsrv.listenaddr 192.168.71.${ip_last} --telnetsrv.listenport ${telnet_port}
    depends_on:
      - oai-gnb
    networks:
      public_net:
        ipv4_address: 192.168.71.${ip_last}
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ../../conf_files/nrue_recap/nrue${idx}.uicc.yaml:/opt/oai-nr-ue/etc/nr-ue.yaml:ro
      - ./scripts/ue_mmtc_entrypoint.sh:/opt/oai-nr-ue/bin/entrypoint.sh:ro
    healthcheck:
      test: /bin/bash -c "pgrep nr-uesoftmodem"
      start_period: 10s
      start_interval: 500ms
      interval: 10s
      timeout: 5s
      retries: 5

EOF
done

echo "Generated mMTC overlay: $OUTPUT_FILE (UE1..UE${TOTAL_UES})"
