#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$PROJECT_DIR/../../../.." && pwd)"
PAPER_DIR="$REPO_ROOT/redcap_doc/evaluation_papers/redcap_vaildation_BWP_SDT"
OUT_DIR="$PROJECT_DIR/exp_result/paper_figures"
DPI="${DPI:-140}"

command -v pdftoppm >/dev/null

mkdir -p "$OUT_DIR/paper1_BWP_switching" "$OUT_DIR/paper2_SDT_small_data"

pdftoppm -png -r "$DPI" "$PAPER_DIR/paper1_BWP_switching.pdf" "$OUT_DIR/paper1_BWP_switching/page"
pdftoppm -png -r "$DPI" "$PAPER_DIR/paper2_SDT_small_data.pdf" "$OUT_DIR/paper2_SDT_small_data/page"

cat > "$OUT_DIR/README.md" <<EOF
# Rendered Paper Pages For Curve Digitization

- [Generated By]: \`scripts/render_paper_figures.sh\`
- [DPI]: $DPI
- [Paper 1]: \`paper1_BWP_switching/page-*.png\`
- [Paper 2]: \`paper2_SDT_small_data/page-*.png\`
- [Next Step]: read numeric points from the relevant figures and update \`../paper_curve_digitization_template.csv\`.

## Figure Targets

| Paper | Figure | Metric |
|---|---|---|
| paper1_BWP_switching | Fig. 3 | application-layer throughput, high load |
| paper1_BWP_switching | Fig. 4 | Default BWP ratio, high load |
| paper1_BWP_switching | Fig. 5 | Default BWP ratio, low load |
| paper1_BWP_switching | Fig. 6 | estimated power saving |
| paper1_BWP_switching | Fig. 7 | mean PDU scheduling delay |
| paper2_SDT_small_data | Fig. 3 | success probability versus time slot |
| paper2_SDT_small_data | Fig. 4 | success probability versus device intensity |
EOF

echo "wrote $OUT_DIR"
